AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Audio Transcription Pipeline with S3, DynamoDB, Lambda, and Transcribe

Globals:
  Function:
    Runtime: python3.10
    Timeout: 60
    MemorySize: 512

Resources:

  ## DynamoDB Table
  TranscriptionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Transcriptions
      AttributeDefinitions:
        - AttributeName: file_id
          AttributeType: S
      KeySchema:
        - AttributeName: file_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ## S3 Bucket
  AudioBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: audio-transcription-pipeline-bucket
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt TranscriptionLambda.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: uploads/

  ## S3 Bucket Policy for Transcribe
  AudioBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AudioBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowTranscribeRead
            Effect: Allow
            Principal:
              Service: transcribe.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${AudioBucket.Arn}/uploads/*"

  ## Lambda #1 - Start Transcribe
  TranscriptionLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TranscriptionLambda
      CodeUri: ../backend/
      Handler: lambda_handler.lambda_handler
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
        - AmazonTranscribeFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref TranscriptionsTable
          BUCKET_NAME: !Ref AudioBucket

  ## Lambda #2 - Update DynamoDB
  UpdateLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TranscriptionUpdateLambda
      CodeUri: backend/
      Handler: update_lambda.lambda_handler
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Events:
        S3Processed:
          Type: S3
          Properties:
            Bucket: !Ref AudioBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: processed/
                  - Name: suffix
                    Value: .json
